[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "log_analyzer"
version = "0.0.1"
description = "0TU5 first homework"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pre-commit>=4.2.0",
    "structlog>=25.2.0",
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "flake8",
    "mypy",
    "pytest",
    "pytest-cov",
]

[project.scripts]
log-analyzer = "log_analyzer.main:main"

[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.setuptools]
packages = { find = { where = ["log_analyzer"] } }
